server:
  port: ${apiPort:9898}

mongodb:
  uri: "mongodb://127.0.0.1:27017"
  database: trace_db

logging:
  config: classpath:log4j2.yml

management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health, metrics"
  metrics:
    export:
      prometheus:
        enabled: true